### PR TITLE
Move cross-env to devDependencies

### LINKED ISSUE #237: move `cross-env` to devDependencies
Since `cross-env` is only used in build stage, it should be moved to devDependencies.

### PR DESCRIPTION
**Pull request by bluwy**
Closes #237

### CODE REVIEW

**Comment by Richienb** [comment]
// @gka

**Comment by t-ricci-enhancers** [comment]
Please merge @gka

**Comment by bluwy** [comment]
@gka Any chance you can take another look at this? Your package has around a million downloads monthly and resolving this would save tons of unnecessary bytes downloaded.

**Comment by bluwy** [comment]
Looks like #279 was merged instead, but anyways glad to see this fixed.

**Pull request closed without merging**
