### PR TITLE
Support case-insensitive colorbrewer lookups

### PR DESCRIPTION
**Pull request by rymohr**
Allows colorbrewer scales to be found by lowercase name. 

The original case is fine for developers but when you start exposing them to end-users it can get annoying. Whether you use `blues` or `Blues` the intent is clear. This permits both options.

Thanks for the great library!

### CODE REVIEW

**Comment by gka** [comment]
Agree, though I think the implementation could be a little shorter.

I think we should *either* add lowercase aliases for the keys in chroma.brewer.* *or* test for lowercase input in `scale.setColors`. Doing both feels like too much.

Personally I would lean towards only doing the lowercase lookup in `setColors` and not adding the aliases. Adding the lowercase aliases makes it a bit harder to use in environments where you have auto-completion, such as the browser console or in interactive node interpreters.

**Comment by rymohr** [comment]
That was my initial approach but some of those colorbrewer names look awful lowercased.  Much easier to read with the mixed case.

That said, the coffee-side implementation change itself is only 2 lines. Not sure if fretting about shortness is warranted here.

**Comment by gka** [comment]
so what I am suggesting is to only keep [this change](https://github.com/gka/chroma.js/pull/77/files#diff-a6718515a56951fe155205bc89854c40R30) but don't add the lowercase aliasses. think that's ok?

**Comment by rymohr** [comment]
I might be missing something obvious here, but I'm pretty sure that will only work if you lowercase the [original colorbrewer definitions](https://github.com/rymohr/chroma.js/blob/master/src/colors/colorbrewer.coffee) too.

**Comment by gka** [comment]
ahh, sorry,  you're right :)

will take a look at this to see what else can be done.. thx

**Comment by gka** [comment]
merged in d77c2d4fbde6701dfdf003400400972284b2cae7

**Pull request closed without merging**
